# Generated by Django 5.1.4 on 2025-01-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('symptoms', models.CharField(max_length=255)),
                ('treatment', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
