# Generated by Django 5.1.4 on 2025-01-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_doctor', '0002_rename_username_user_name_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disease',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
