# Generated by Django 5.1.4 on 2025-01-23 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_doctor', '0004_treatment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='user',
        ),
        migrations.AddField(
            model_name='treatment',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='treatment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='personal_doctor.treatment'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='disease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='personal_doctor.disease'),
        ),
        migrations.AlterField(
            model_name='user',
            name='disease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='personal_doctor.disease'),
        ),
    ]
